### ISSUE TITLE
Use imgflip for meme gen instead of memegenerator.net

### ISSUE THREAD

**Issue by knguyen0928** [jbatte47/slack-memebot#3]
memegenerator.net is slow and buggy, while imgflip seems to have a better api https://api.imgflip.com/

**Comment by jbatte47** [comment]
True on both counts, but with one parameterless `get_memes` method that returns whatever the hell imgflip thinks it should and a `caption_image` method that requires a total of 14 parameters to place two lines of text, I can't reproduce the functionality I have with memegenerator. Not even close. That's why an internal image generator is on the agenda: https://trello.com/c/YA80ELhZ

BTW, by the time the generator is next up, slack-memebot will most likely have graduated into a series of microservices running on AWS, with a Mongo or similar db backing it. At that point, a Lambda function will most likely take on this responsibility, which will theoretically put its throughput through the proverbial roof.

We'll get there!
